# Generated by Django 4.1.7 on 2023-06-15 15:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_vendordetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='vendorDetails',
            new_name='vendorDetail',
        ),
    ]
