# Generated by Django 4.1.7 on 2023-06-16 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_productcategory_delete_category_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='vendorDetail',
        ),
    ]
